### ISSUE TITLE
Dependency Review

### ISSUE THREAD

**Issue by MPV** [scalacenter/sbt-dependency-submission#135]
Does this action work together with GitHub's Dependency Review?

See:
- https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review
- https://github.com/actions/dependency-review-action

**Comment by adpi2** [comment]
There is a note in [Dependency review enforcement](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement) stating that it should work:

> Note: The dependency review API and the dependency submission API work together. This means that the dependency review API will include dependencies submitted via the dependency submission API. This feature is currently in public beta and subject to change.

If anyone knows how to set them up, we could add it as an example in the [README.md](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement).

**Comment by MPV** [comment]
A basic example (in my mind) should be) — would you agree?
```yaml
name: Dependency Review

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: write # for submitting dependency graph

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: scalacenter/sbt-dependency-submission@v2
      - uses: actions/dependency-review-action@v3
        if: github.event_name == 'pull_request'
```
