### ISSUE TITLE
Dependencies are not in organization dependency overview

### ISSUE THREAD

**Issue by johnpangalos** [scalacenter/sbt-dependency-submission#139]
Hey, when I use this action my dependencies do not show up in my organization overview (i.e. 
https://github.com/orgs/{org_name}/insights/dependencies) but they do show up in my repos dependency graph page (i.e. https://github.com/{org_name}/{repo_name}/network/dependencies). Repositories that generate an dependency graph automatically seem to populate to the organization overview correctly (e.g. maven, npm).

Is this expected behavior?

Here is my workflow:

``` yaml
name: Update Dependency Graph

on:
  push:
    branches:
      - master

jobs:
  dependency-graph:
    name: Update Dependency Graph
    permissions:
      contents: write # this permission is needed to submit the dependency graph
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: coursier/cache-action@d1039466d0812d6370649b9afb02bbf5f646bacf # v6.4.3
      - uses: coursier/setup-action@48280172a2c999022e42527711d6b28e4945e6f0 # v1.3.4
        with:
          apps: sbt
      - uses: scalacenter/sbt-dependency-submission@1eef19c779b0b4722ab3d72b4e52279070ac7945 # v2.2.0
```

Any help with this would be greatly appreciated.
