### ISSUE TITLE
Cannot read dependencies from a private GitHub repository

### ISSUE THREAD

**Issue by OndrejSpanel** [scalacenter/sbt-dependency-submission#55]
I tried to installed this action into a workflow of a private repository. It seems to work mostly fine, but the action seems unable to download a library which is located in private GitHub packages.

The attempt to access the directory is made, but it results in an error, like this:

> https://maven.pkg.github.com/organization/_/net/organization/library_2.13/1.2.3/library_2.13-1.2.3.pom

The library exists at that location, but private credentials (a proper GitHub token) are required to access it.

Would it be possible either to tell the action to use a custom GitHub token to access the dependencies, or to skip this particular dependency somehow, so that I can list the public dependencies for the project?

**Comment by OndrejSpanel** [comment]
It seems to option to provide a token is already present, only not documented:

```yaml
  token:
    description: GitHub Personal Access Token (PAT). Defaults to PAT provided by Action runner.
    required: false
    default: ${{ github.token }}
```
