### ISSUE TITLE
fatal: could not read Username for 'https://github.com': No such file or directory

### ISSUE THREAD

**Issue by felickz** [scalacenter/sbt-dependency-submission#69]
For dependencies that reference another private repo.. 

Is the [`token` input](https://github.com/scalacenter/sbt-dependency-submission#--token-optional) intended to resolve this error or will a git config need to be added to specify a token for each repo?

**Comment by adpi2** [comment]
Thanks for opening this issue!

It is likely indeed that sbt cannot use the token input to resolve private git repositories. But I would like to make it work.

Does anyone know how to solve this?

**Comment by jackgkafaty** [comment]
Hi @adpi2 & @felickz!

To solve this issue you must add the following step which is needed to for git clone to work in this scenario. 
```
steps:
      - name: Configure git
        env:
          TOKEN: ${{ secrets.PAT }}
        run: git config --global url."https://${TOKEN}:[x-oauth-basic@github.com](mailto:x-oauth-basic@github.com)/".insteadOf "https://github.com/"
```

```
name: Scala Dependency Graph Generation for Dependabot
 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      security-events: write
    steps:
      - name: Configure git
        env:
          TOKEN: ${{ secrets.PAT }}
        run: git config --global url."https://${TOKEN}:[x-oauth-basic@github.com](mailto:x-oauth-basic@github.com)/".insteadOf "https://github.com/"
      - uses: actions/checkout@v3
      - uses: scalacenter/sbt-dependency-submission@v2.0.1
        with:
          token: ${{ secrets.PAT }}
```
