### ISSUE TITLE
Possible to submit multiple, independent projects?

### ISSUE THREAD

**Issue by mkurz** [scalacenter/sbt-dependency-submission#84]
Sorry for my ignorance in case that is possible anyway and I just couldn't figure it out or was misconfiguring things or was discussed already.

Let's say I have a repository with two independent projects `project_a/build.sbt` and `project_b/build.sbt`.
Can I submit both of those `build.sbt` files to GitHub so they show up independent in the /network/dependencies view?
I tried that with the Play Framework were we have a `build.sbt` and a `documentation/build.sbt`, but in the GitHub UI only the `build.sbt` shows up.
The workflow: https://github.com/playframework/playframework/blob/3c21f31f28c27ad00c9495096fa60e25a4b67050/.github/workflows/dependency-graph.yml#L24-L27

I think this has to be possible somehow because in our Dependency UI it shows all our (multiple) yml workflow files already.

**Comment by adpi2** [comment]
Thanks for opening this issue. It should indeed be possible to submit multiple independent projects but currently it is not.

The problem is that currently all manifests are declared as coming from a single build file `build.sbt`:
https://github.com/scalacenter/sbt-dependency-submission/blob/04f2579de8e5d7ce6049129ff1b6912520d21dfd/sbt-plugin/src/main/scala/ch/epfl/scala/GithubDependencyGraphPlugin.scala#L186-L187

I thing we can fix this by comparing the sbt `baseDirectory` with the `GITHUB_WORKSPACE` from [Github default env variables](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables).

**Comment by mkurz** [comment]
@adpi2 Thanks! Would be nice to have this working :wink:

**Comment by mkurz** [comment]
Thanks for fixing. However how does that actually work now?
Do I need to run a separate step for each project? E.g.
```yml
...
steps:
  - uses: actions/checkout@v3
  - uses: scalacenter/sbt-dependency-submission@v2
    with:
      working-directory: ./my-scala-project-one
  - uses: scalacenter/sbt-dependency-submission@v2
    with:
      working-directory: ./my-scala-project-two
```
Or does the action detect all `build.sbt` files automatically?
